import {useEffect,useRef} from "react";
import * as THREE from "three";
import {Bar} from "react-chartjs-2";
import {Chart as ChartJS,CategoryScale,LinearScale,BarElement,Tooltip,Legend} from "chart.js";
ChartJS.register(CategoryScale,LinearScale,BarElement,Tooltip,Legend);

function NeuralScene(){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const host=ref.current;if(!host)return;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(52,host.clientWidth/host.clientHeight,.1,100);camera.position.z=8;
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);
 const group=new THREE.Group();scene.add(group);
 group.add(new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,4),new THREE.MeshBasicMaterial({color:0x9d7cff,wireframe:true,transparent:true,opacity:.72})));
 group.add(new THREE.Mesh(new THREE.SphereGeometry(1.02,32,32),new THREE.MeshBasicMaterial({color:0x5c32ff,transparent:true,opacity:.14})));
 const pts=new Float32Array(800*3);for(let i=0;i<800;i++){const r=2.1+Math.random()*2.8,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);pts[i*3]=r*Math.sin(b)*Math.cos(a);pts[i*3+1]=r*Math.sin(b)*Math.sin(a);pts[i*3+2]=r*Math.cos(b)}
 const geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.BufferAttribute(pts,3));group.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0xc8baff,size:.026,transparent:true,opacity:.68})));
 const ring=new THREE.Mesh(new THREE.TorusGeometry(2.35,.012,12,160),new THREE.MeshBasicMaterial({color:0x7c5cff,transparent:true,opacity:.55}));ring.rotation.x=Math.PI/2.6;group.add(ring);
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener("resize",resize);
 let id=0;const tick=()=>{id=requestAnimationFrame(tick);group.rotation.y+=.0028;group.rotation.x=Math.sin(performance.now()*.00025)*.08;ring.rotation.z+=.004;renderer.render(scene,camera)};tick();
 return()=>{cancelAnimationFrame(id);removeEventListener("resize",resize);renderer.dispose();host.removeChild(renderer.domElement)}},[]);
 return <div ref={ref} className="scene"/>;
}
const data={labels:["Reasoning","Coding","Vision","Long context","Tool use"],datasets:[{label:"Astra 6",data:[96,98,94,97,99],backgroundColor:"rgba(150,118,255,.8)",borderRadius:8},{label:"Previous generation",data:[82,86,79,84,81],backgroundColor:"rgba(255,255,255,.12)",borderRadius:8}]};
const options={responsive:true,plugins:{legend:{labels:{color:"#aaa"}}},scales:{x:{ticks:{color:"#777"},grid:{display:false}},y:{min:0,max:100,ticks:{color:"#777",callback:(v:number)=>v+"%"},grid:{color:"rgba(255,255,255,.06)"}}}};
export default function App(){return <main>
<nav><div className="brand"><span className="orb"/>ASTRA <b>6</b></div><div className="navlinks"><a href="#capabilities">Capabilities</a><a href="#benchmarks">Benchmarks</a><a href="#architecture">Architecture</a></div><button className="pill">Explore model ↗</button></nav>
<section className="hero"><div className="hero-copy"><div className="eyebrow">NEXT-GENERATION INTELLIGENCE <span>DEMO</span></div><h1>Intelligence that<br/><em>moves with you.</em></h1><p>Astra 6 is a fictional showcase model built for this interactive demo — designed to visualize what an ambitious frontier system could feel like.</p><div className="actions"><button className="primary" onClick={()=>document.querySelector("#benchmarks")?.scrollIntoView({behavior:"smooth"})}>See the evidence ↓</button><button className="ghost" onClick={()=>document.querySelector("#architecture")?.scrollIntoView({behavior:"smooth"})}>Explore architecture</button></div><div className="metrics"><div><strong>99.2%</strong><span>Tool-use reliability*</span></div><div><strong>1.8M</strong><span>Context window*</span></div><div><strong>14ms</strong><span>Visual response*</span></div></div></div><div className="hero-visual"><NeuralScene/><div className="orbit-label l1">REASONING CORE</div><div className="orbit-label l2">MULTIMODAL</div><div className="orbit-label l3">AGENTIC</div></div></section>
<section id="capabilities" className="section"><div className="section-head"><div><span className="eyebrow">01 / CAPABILITIES</span><h2>One model.<br/><em>Many dimensions.</em></h2></div><p>Built as a visual concept, Astra 6 treats intelligence as a coordinated system: reasoning, perception, memory and action working together.</p></div><div className="cards">{[["01","Deep reasoning","Breaks complex problems into structured steps, evaluates alternatives and keeps the objective in view."],["02","Native multimodality","Text, images, diagrams and interfaces become one shared representation rather than separate tools."],["03","Agentic execution","Plans, calls tools, observes results and adapts — turning an answer into an outcome."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="benchmarks" className="section"><div className="section-head"><div><span className="eyebrow">02 / BENCHMARKS</span><h2>Numbers with<br/><em>context.</em></h2></div><p>Illustrative benchmark scores for the fictional Astra 6 concept. They are intentionally not presented as real-world measurements.</p></div><div className="chart-card"><div className="chart-top"><div><strong>Capability index</strong><span>Illustrative / normalized to 100</span></div><div className="live"><i/>LIVE SIMULATION</div></div><Bar data={data} options={options}/></div></section>
<section id="architecture" className="section"><div className="architecture-grid"><div><span className="eyebrow">03 / ARCHITECTURE</span><h2>A system built<br/>to <em>think.</em></h2><p>Imagine a coordinated stack where a reasoning engine routes context through perception, memory and tool interfaces — with feedback continuously shaping the next action.</p></div><div className="stack">{[["01","PERCEPTION","Vision · Audio · Text"],["02","REASONING","Planning · Verification · Synthesis"],["03","MEMORY","Context · Retrieval · State"],["04","ACTION","Tools · Code · Interfaces"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></div></section>
<footer><div className="brand"><span className="orb"/>ASTRA <b>6</b></div><span>Concept interface · React + TypeScript + Three.js + Chart.js</span><span>© 2026 Demo</span></footer>
</main>}