import {useEffect,useRef} from "react";
import * as THREE from "three";
import {Bar} from "react-chartjs-2";
import {Chart as ChartJS,CategoryScale,LinearScale,BarElement,Tooltip,Legend,ChartOptions} from "chart.js";
ChartJS.register(CategoryScale,LinearScale,BarElement,Tooltip,Legend);

function NeuralScene(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const host=ref.current;if(!host)return;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(52,host.clientWidth/host.clientHeight,.1,100);camera.position.z=8;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);const group=new THREE.Group();scene.add(group);group.add(new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,4),new THREE.MeshBasicMaterial({color:0x9d7cff,wireframe:true,transparent:true,opacity:.72})));group.add(new THREE.Mesh(new THREE.SphereGeometry(1.02,32,32),new THREE.MeshBasicMaterial({color:0x5c32ff,transparent:true,opacity:.14})));const pts=new Float32Array(800*3);for(let i=0;i<800;i++){const r=2.1+Math.random()*2.8,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);pts[i*3]=r*Math.sin(b)*Math.cos(a);pts[i*3+1]=r*Math.sin(b)*Math.sin(a);pts[i*3+2]=r*Math.cos(b)}const geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.BufferAttribute(pts,3));group.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0xc8baff,size:.026,transparent:true,opacity:.68})));const ring=new THREE.Mesh(new THREE.TorusGeometry(2.35,.012,12,160),new THREE.MeshBasicMaterial({color:0x7c5cff,transparent:true,opacity:.55}));ring.rotation.x=Math.PI/2.6;group.add(ring);const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener("resize",resize);let id=0;const tick=()=>{id=requestAnimationFrame(tick);group.rotation.y+=.0028;group.rotation.x=Math.sin(performance.now()*.00025)*.08;ring.rotation.z+=.004;renderer.render(scene,camera)};tick();return()=>{cancelAnimationFrame(id);removeEventListener("resize",resize);renderer.dispose();host.removeChild(renderer.domElement)}},[]);return <div ref={ref} className="scene"/>}

const data={labels:["ARC-AGI-3","ARC-AGI-2","OSWorld 2.0","ScreenSpot-Pro","BrowseComp","AutomationBench"],datasets:[{label:"GPT-6 Astra",data:[99.9,95,72.6,92.7,91.5,41.4],backgroundColor:"rgba(150,118,255,.82)",borderRadius:8}]};
const options: ChartOptions<"bar">={responsive:true,plugins:{legend:{labels:{color:"#aaa"}},tooltip:{callbacks:{label:(ctx)=>ctx.raw+"%"}}},scales:{x:{ticks:{color:"#777",maxRotation:30,minRotation:20},grid:{display:false}},y:{min:0,max:100,ticks:{color:"#777",callback:(v)=>String(v)+"%"},grid:{color:"rgba(255,255,255,.06)"}}}};

export default function App(){return <main>
<nav><div className="brand"><span className="orb"/>GPT-6 <b>ASTRA</b></div><div className="navlinks"><a href="#capabilities">Capabilities</a><a href="#benchmarks">Benchmarks</a><a href="#specs">Specs</a></div><button className="pill" onClick={()=>window.open("https://developers.openai.com/api/docs/models/gpt-6-astra","_blank")}>API docs ↗</button></nav>
<section className="hero"><div className="hero-copy"><div className="eyebrow">GPT-6 FAMILY <span>ASTRA</span></div><h1>Built for the<br/><em>hardest work.</em></h1><p>GPT-6 Astra is OpenAI's flagship model for demanding reasoning, coding, computer use, research and professional workflows.</p><div className="actions"><button className="primary" onClick={()=>document.querySelector("#benchmarks")?.scrollIntoView({behavior:"smooth"})}>View benchmarks ↓</button><button className="ghost" onClick={()=>document.querySelector("#specs")?.scrollIntoView({behavior:"smooth"})}>Explore specs</button></div><div className="metrics"><div><strong>1.05M</strong><span>CONTEXT TOKENS</span></div><div><strong>128K</strong><span>MAX OUTPUT</span></div><div><strong>$10</strong><span>INPUT / 1M TOKENS</span></div></div></div><div className="hero-visual"><NeuralScene/><div className="orbit-label l1">REASONING</div><div className="orbit-label l2">COMPUTER USE</div><div className="orbit-label l3">AGENTS</div></div></section>
<section id="capabilities" className="section"><div className="section-head"><div><span className="eyebrow">01 / CAPABILITIES</span><h2>One model.<br/><em>Many frontiers.</em></h2></div><p>OpenAI positions Astra for complex reasoning, coding, computer use, research and end-to-end professional work, with web search, file search, computer use and other tools supported.</p></div><div className="cards">{[["01","Reasoning","Built for complex problems with configurable reasoning effort from low through max."],["02","Computer use","Supports computer-use workflows and multi-step interaction with software and browsers."],["03","Tool orchestration","Supports web search, file search, code interpreter, hosted shell, MCP and tool search."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="benchmarks" className="section"><div className="section-head"><div><span className="eyebrow">02 / PUBLISHED EVALUATIONS</span><h2>Real results.<br/><em>Real context.</em></h2></div><p>Scores below are published by OpenAI for GPT-6 Astra. Benchmark methodologies, harnesses and evaluation dates matter, so the numbers should not be treated as a universal ranking.</p></div><div className="chart-card"><div className="chart-top"><div><strong>Selected OpenAI-reported benchmarks</strong><span>Score · percent · source: OpenAI</span></div><div className="live"><i/>PUBLISHED DATA</div></div><Bar data={data} options={options}/><small className="note">Source: OpenAI GPT-6 Astra System Card. Scores can change when evaluations are revised.</small></div></section>
<section id="specs" className="section"><div className="architecture-grid"><div><span className="eyebrow">03 / MODEL PROFILE</span><h2>Designed for<br/><em>scale.</em></h2><p>Astra has a 1,050,000-token context window, 128,000 maximum output tokens, and supports low, medium, high, xhigh and max reasoning effort. Its listed knowledge cutoff is April 30, 2026.</p></div><div className="stack">{[["01","CONTEXT","1,050,000 tokens"],["02","OUTPUT","128,000 tokens max"],["03","REASONING","Low · Medium · High · xhigh · Max"],["04","TOOLS","Web · Files · Code · Computer · MCP"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></div></section>
<footer><div className="brand"><span className="orb"/>GPT-6 <b>ASTRA</b></div><span>Interactive model showcase · React + TypeScript + Three.js + Chart.js</span><span>Data checked Sep 30, 2026</span></footer>
</main>}